// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnjedthogneabljhykju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuamVkdGhvZ25lYWJsamh5a2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTU4MjUsImV4cCI6MjA2NzM3MTgyNX0.V4re8JqQbKoL9sXPfXU_N4hcSkj4jrKHAokQ7t92kB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});